<a href="https://colab.research.google.com/github/yallavaibhav/Comic-AudioBooks/blob/master/Text_detection_without_preprocess.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np
from tqdm.notebook import tqdm
import matplotlib.pyplot as plt
from PIL import Image

Method1: Pytesseract

In [7]:
!sudo apt-get install tesseract-ocr

Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  tesseract-ocr-eng tesseract-ocr-osd
The following NEW packages will be installed:
  tesseract-ocr tesseract-ocr-eng tesseract-ocr-osd
0 upgraded, 3 newly installed, 0 to remove and 23 not upgraded.
Need to get 4,850 kB of archives.
After this operation, 16.3 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu focal/universe amd64 tesseract-ocr-eng all 1:4.00~git30-7274cfa-1 [1,598 kB]
Get:2 http://archive.ubuntu.com/ubuntu focal/universe amd64 tesseract-ocr-osd all 1:4.00~git30-7274cfa-1 [2,990 kB]
Get:3 http://archive.ubuntu.com/ubuntu focal/universe amd64 tesseract-ocr amd64 4.1.1-2build2 [262 kB]
Fetched 4,850 kB in 1s (4,822 kB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/Fro

In [5]:
pip install pytesseract

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [9]:
import pytesseract
import cv2 as cv

In [11]:
img = cv.imread('/content/Screenshot 2023-02-12 232859.png')
print(pytesseract.image_to_string(img,lang='eng'))

Method2: EasyOCR

In [13]:
pip install easyocr

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.9/2.9 MB 38.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 608.2/608.2 KB 40.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 146.0/146.0 KB 18.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.6/47.6 MB 16.4 MB/s eta 0:00:00
  Attempting uninstall: opencv-python-headless
    Found existing installation: opencv-python-headless 4.7.0.72
    Uninstalling opencv-python-headless-4.7.0.72:
      Successfully uninstalled opencv-python-headless-4.7.0.72


In [14]:
import easyocr
reader = easyocr.Reader(['en'],gpu=False)

Progress: |██████████████████████████████████████████████████| 100.0% Complete

Progress: |██████████████████████████████████████████████████| 100.0% Complete

In [26]:
img2 = cv.imread('/content/Screenshot 2023-03-18 235327.png')
img3 = cv.imread('/content/Screenshot 2023-03-18 235352.png')
img4 = cv.imread('/content/Screenshot 2023-03-18 235431.png')
img5 = cv.imread('/content/Screenshot 2023-03-18 235458.png')

In [28]:
results = reader.readtext(img2)

In [29]:
results

[([[20, 8], [308, 8], [308, 34], [20, 34]],
  'Using HeR WEATHER-',
  0.5742574158625449),
 ([[17, 29], [327, 29], [327, 65], [17, 65]],
  'ContROlling Abilities;',
  0.20875050332355527),
 ([[18, 60], [326, 60], [326, 88], [18, 88]],
  'Storm GREATES AGusT',
  0.3730667174723233),
 ([[20, 86], [348, 86], [348, 114], [20, 114]],
  'Of ind 10 Help A truck',
  0.2817194967591711),
 ([[18, 116], [262, 116], [262, 142], [18, 142]],
  'LAND SAFELY CNnA',
  0.2011025932521003),
 ([[16, 140], [210, 140], [210, 170], [16, 170]],
  'BaASe Beldw:',
  0.21762622774060422)]

In [30]:
results[0]

([[20, 8], [308, 8], [308, 34], [20, 34]],
 'Using HeR WEATHER-',
 0.5742574158625449)

In [31]:
pd.DataFrame(results, columns=['bbox','text','confidence'])

bbox                    text  \
0        [[20, 8], [308, 8], [308, 34], [20, 34]]      Using HeR WEATHER-   
1      [[17, 29], [327, 29], [327, 65], [17, 65]]  ContROlling Abilities;   
2      [[18, 60], [326, 60], [326, 88], [18, 88]]     Storm GREATES AGusT   
3    [[20, 86], [348, 86], [348, 114], [20, 114]]  Of ind 10 Help A truck   
4  [[18, 116], [262, 116], [262, 142], [18, 142]]        LAND SAFELY CNnA   
5  [[16, 140], [210, 140], [210, 170], [16, 170]]            BaASe Beldw:   

   confidence  
0    0.574257  
1    0.208751  
2    0.373067  
3    0.281719  
4    0.201103  
5    0.217626

In [36]:
results = reader.readtext(img3)
pd.DataFrame(results, columns=['bbox','text','confidence'])

bbox                    text  \
0  [[36, 232], [319, 232], [319, 262], [36, 262]]   STAY Hepe  GENTLEMEN_   
1  [[28, 257], [336, 257], [336, 289], [28, 289]]  The river REScue TEAMS   
2  [[44, 284], [264, 284], [264, 314], [44, 314]]        Will Be Arriving   
3  [[89, 311], [269, 311], [269, 339], [89, 339]]            MOMENTArily,   

   confidence  
0    0.437648  
1    0.281444  
2    0.648963  
3    0.311495

In [37]:
results = reader.readtext(img4)
pd.DataFrame(results, columns=['bbox','text','confidence'])

bbox  text  confidence
0       [[247, 0], [520, 0], [520, 120], [247, 120]]  Boon    0.122504
1     [[443, 93], [522, 93], [522, 129], [443, 129]]  WHAC    0.460143
2   [[452, 124], [522, 124], [522, 156], [452, 156]]   THA    0.993060
3  [[-12.808976707313633, 12.091130597595036], [2...  3zoM    0.111804

In [38]:
results = reader.readtext(img5)
pd.DataFrame(results, columns=['bbox','text','confidence'])

bbox      text  confidence
0  [[50, 114], [146, 114], [146, 146], [50, 146]]      Stop    0.161567
1  [[38, 142], [184, 142], [184, 174], [38, 174]]  MUTANTS;    0.524843

Method 3: Keras_OCR

In [18]:
pip install keras_ocr

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.3/42.3 KB 5.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.5/9.5 MB 25.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.7/50.7 KB 7.1 MB/s eta 0:00:00
  Created wheel for validators: filename=validators-0.20.0-py3-none-any.whl size=19579 sha256=4d354f2e8c896a79343216689bfec8295127c5615776b3c0c9a02c468d73ef28
  Stored in directory: /root/.cache/pip/wheels/2d/f0/a8/1094fca7a7e5d0d12ff56e0c64675d72aa5cc81a5fc200e849
Successfully built validators


In [19]:
import keras_ocr
pipeline = keras_ocr.pipeline.Pipeline()

Looking for /root/.keras-ocr/craft_mlt_25k.h5
Looking for /root/.keras-ocr/crnn_kurapan.h5


In [20]:
pipeline.recognize([img])

1/1 [==============================] - 4s 4s/step


[[('herem', array([[20., 22.],
          [68., 22.],
          [68., 34.],
          [20., 34.]], dtype=float32))]]

In [32]:
pipeline.recognize([img2])

1/1 [==============================] - 5s 5s/step


[[('her', array([[110.,  10.],
          [165.,  10.],
          [165.,  31.],
          [110.,  31.]], dtype=float32)), ('using', array([[ 23.,  11.],
          [104.,  11.],
          [104.,  32.],
          [ 23.,  32.]], dtype=float32)), ('weaher', array([[170.,  11.],
          [298.,  11.],
          [298.,  32.],
          [170.,  32.]], dtype=float32)), ('e', array([[296.,  19.],
          [305.,  19.],
          [305.,  26.],
          [296.,  26.]], dtype=float32)), ('controlling',
   array([[ 22.      ,  36.999992],
          [190.99997 ,  36.999992],
          [190.99997 ,  58.999992],
          [ 22.      ,  58.999992]], dtype=float32)), ('abilities',
   array([[198.16812 ,  36.552105],
          [324.2734  ,  38.12842 ],
          [323.9608  ,  63.137012],
          [197.8555  ,  61.560696]], dtype=float32)), ('creates',
   array([[111.,  64.],
          [227.,  64.],
          [227.,  86.],
          [111.,  86.]], dtype=float32)), ('soem', array([[ 20.,  65.],
         

In [33]:
pipeline.recognize([img3])

1/1 [==============================] - 3s 3s/step


[[('stay', array([[ 38.482895, 236.83376 ],
          [ 96.90604 , 235.33571 ],
          [ 97.48357 , 257.85938 ],
          [ 39.060425, 259.35742 ]], dtype=float32)),
  ('here', array([[ 99., 236.],
          [170., 236.],
          [170., 260.],
          [ 99., 260.]], dtype=float32)),
  ('gentlemen', array([[176.99998, 236.     ],
          [318.99994, 236.     ],
          [318.99994, 258.     ],
          [176.99998, 258.     ]], dtype=float32)),
  ('the', array([[ 31., 261.],
          [ 80., 261.],
          [ 80., 284.],
          [ 31., 284.]], dtype=float32)),
  ('rescue', array([[155.74794, 262.0967 ],
          [251.94417, 260.81412],
          [252.27052, 285.28976],
          [156.0743 , 286.57236]], dtype=float32)),
  ('river', array([[ 82., 262.],
          [154., 262.],
          [154., 285.],
          [ 82., 285.]], dtype=float32)),
  ('teams', array([[256.2822 , 262.6192 ],
          [333.69455, 259.75208],
          [334.57535, 283.53424],
          [257.163  , 

In [34]:
pipeline.recognize([img4])

1/1 [==============================] - 1s 800ms/step


[[('hoomeom', array([[-13.5852165,  41.63274  ],
          [507.76367  , -34.224854 ],
          [525.98376  ,  90.9971   ],
          [  4.6348877, 166.85469  ]], dtype=float32)),
  ('wha', array([[446.,  98.],
          [521.,  98.],
          [521., 127.],
          [446., 127.]], dtype=float32)),
  ('tha', array([[455., 129.],
          [521., 129.],
          [521., 156.],
          [455., 156.]], dtype=float32))]]

In [35]:
pipeline.recognize([img5])

1/1 [==============================] - 0s 448ms/step


[[('stop', array([[ 51., 116.],
          [142., 116.],
          [142., 145.],
          [ 51., 145.]], dtype=float32)),
  ('mutantsi', array([[ 39.864635, 146.59052 ],
          [192.8662  , 138.4768  ],
          [194.63332 , 171.79977 ],
          [ 41.63176 , 179.91348 ]], dtype=float32))]]